### PR TITLE
Add Xcode project

### PR DESCRIPTION
**Pull request by ianpartridge**
Many people will find this project easier to explore if they can just open an Xcode project up.

### CODE REVIEW

**Comment by tanner0101** [comment]
I think this might create issues as SPM's Xcode projects are specifically meant to be ignored. (contents of `*.pc` files may vary across different computers for example) 

Anyone w/ Xcode installed on their mac can run `swift package generate-xcodeproj; open *.xcodeproj` to generate an open and Xcode project created for their specific environment.

**Comment by carlbrown** [comment]
I'm with @tanner0101 here.  Unless there's something non-standard that needs to happen in the xcodeproj file (Like the way that the `swift-corelibs-foundation` test target has to be configured by hand), I think telling people to run `swift package generate-xcodeproj` is a better solution.

**Comment by ianpartridge** [comment]
My intention was to follow up this PR with another adding [support for getting Swiftlint warnings and errors in Xcode](https://github.com/realm/SwiftLint#xcode). Would people find that useful (I would)?

**Comment by seabaylea** [comment]
I think my preference would be towards not including the Xcode project, but starting to add documentation on how to contribute/develop.

**Comment by ianpartridge** [comment]
OK!

**Pull request closed without merging**
