### PR TITLE
Remove API docs

### PR DESCRIPTION
**Pull request by ianpartridge**
Now that #26 is merged, we should update the API docs accordingly.

This PR fixes a few other minor doc-related things too:

1. Remove `LIBRARY_SEARCH_PATHS=.build/debug` from `.jazzy.yml`. This used to be required when running Jazzy in pre-Swift 3 history, but is now unnecessary.

2. Remove references to `WebAppContaining` and `WebApp` from the docs categories.

3. Extra line in `HTTPCommon.swift` so that Jazzy renders the example code correctly.

### CODE REVIEW

**Comment by seabaylea** [comment]
As per issue #30, can you retarget this as a PR against the `gh-pages` branch?

**Comment by ianpartridge** [comment]
It'll need splitting up, but yes.

**Comment by ianpartridge** [comment]
I've updated the PR so it has the fixes to `.jazzy.yml` etc. and removes the `docs` directory.

I'll open another PR to update the generated docs on the `gh-pages` branch once this is merged.

**Comment by ianpartridge** [comment]
@aleksey-mashanov FYI

**Comment by seabaylea** [comment]
LGTM. Merging.

**Pull request merged**
