### PR TITLE
no dependencies

### PR DESCRIPTION
**Pull request by tanner0101**
Hoping to start testing out this package w/ Vapor soon and needed a version that supported Swift 4 and didn't have any dependencies.

I know eventually this package should include an HTTP server built on swift-server/transport, but for now having this package import IBM's ecosystem of packages makes it difficult for us to test.

This probably won't get merged, but I thought i'd contribute it back nonetheless. 

- [x] support Swift 4
- [x] remove all dependencies
- [x] include CHTTPParser
- [x] remove reliance on `utils.c`

### CODE REVIEW

**Comment by ianpartridge** [comment]
I would support merging the part of this PR which removes the dependency on https://github.com/IBM-Swift/CHTTPParser.git and adds a `CHTTPParser` target to this package. Or we could create https://github.com/swift-server/CHTTPParser and depend on that.

**Comment by seabaylea** [comment]
Hey @tanner0101 . Yes - we should certainly start to remove the dependencies. 

In the short term we could do this by bringing everything into the project, i.e. bring in a fork of BlueSocket (stripping it back to just the parts that we're using) etc, and then replace those as TLS and networking comes in.

Would that be reasonable?

Note that @ianpartridge has also raised a PR to add a simple/initial `HTTPServer` API so users don't have to create a `BlueSocketSimpleServer` any more.

**Comment by tanner0101** [comment]
@seabaylea yup. that sounds perfectly reasonable to me!

**Comment by carlbrown** [comment]
Hey @tanner0101 - Please go take a look at #39 and see if you think it resolves this PR's issue to the point that it can be closed.

P.S. I know you mentioned Swift 4 above as well - that's going to happen, and soon (see #40), but that need (as necessary as it is) technically doesn't belong on an issue titled "**no dependencies**", so I still think this one should be closable.

**Comment by seabaylea** [comment]
@tanner0101 I think this work has now been superseded. Are you happy for it to be closed?

**Pull request closed without merging**
