### PR TITLE
Add initial set of Jazzy docs

### PR DESCRIPTION
**Pull request by seabaylea**
This adds an initial pass of Jazzy docs for the API. As a side effect this highlighted that we were missing reason phrase strings for a few of the HTTP response status codes.

### CODE REVIEW

**Review by tanner0101 — APPROVED** [review]
screen shot 2017-08-11 at 3 21 54 pm

Nice :) These look great.

**Comment by seabaylea** [comment]
Thanks @tanner0101. Merging.

**Comment by ianpartridge** [comment]
Are these published anywhere, like GitHub Pages?  I looked at http://swift-server.github.io/http

**Comment by seabaylea** [comment]
Not yet - that's next on the list (followed by updating the README.md). Of course, if you want to volunteer....

**Comment by seabaylea** [comment]
As we're currently working in "develop", I've just created a "gh-pages" branch to publish the docs for now. Once we move over to using master then we'll switch to using /docs in master.

**Pull request merged**
