### PR TITLE
Sockets aren't idle if response not completed

### PR DESCRIPTION
**Pull request by carlbrown**
Fixes bug where a long response can be closed if the idle timeout fires while it's in progress

### CODE REVIEW

**Comment by ianpartridge** [comment]
I'm not qualified to review the queueing aspects of this, for example why `responseCompleted` can be safely modified outside the `socketWriterQueue`.

**Review by ianpartridge — COMMENTED** [review]
I'm not qualified to review the queueing aspects of this, for example why `responseCompleted` can be safely modified outside the `socketWriterQueue`.

**Comment by ianpartridge** [comment]
Can we add a test for this bug?

**Comment by carlbrown** [comment]
> why `responseCompleted` can be safely modified outside the `socketWriterQueue`.

`responseCompleted` has its own lock, so it's safe to modify, even in the middle of a request/response.  The trick is that we shouldn't act on that in the middle of a read/write, which is why the `close` calls are still queued instead of happening immediately.

**Comment by seabaylea** [comment]
LGTM. Merging.

**Pull request merged**
