### PR TITLE
modules / namespace

### PR DESCRIPTION
**Pull request by tanner0101**
This PR moves HTTP models into a module named `HTTP`. This allows for the removal of the `HTTP` prefix from type names in situations where there is no ambiguity. It also moves the BlueSocket HTTP driver into its own module that depends on HTTP. This will allow us to ensure correct access control and keep different HTTP implementations separate. It also cleans up the tests, moving them into separate files and laying the ground work for many tests to come.

### CODE REVIEW

**Comment by helje5** [comment]
Could you please split the PR into separate ones? I.e. the module splitting seems nice while removing the HTTP prefix was controversial on the list.

**Comment by paulofaria** [comment]
I agree with Helge. Removing the prefix needs further discussions. I personally prefer without them, but we still need to reach a consensus.

**Comment by tanner0101** [comment]
`HTTP.HTTPVersion` \*eyes bleed\*

@helje5 @paulofaria can you point me to the convo about what makes this controversial? Redundant HTTP seems plainly against Swift API design guidelines.

**Comment by loganwright** [comment]
The prefixing of module is usually a thing, in my experience, within languages that don't provide adequate namespacing .. see: ObjC. In fact, when Swift was introduced, I remember namespacing being lauded by devs and apple alike because we could avoid the namespace prefix on every class.

Here, it seems like a somewhat obvious redundancy, so I'm not sure how this could be controversial. Would also love to hear some of the counterpoints to why we'd want to double up on the HTTP.

**Comment by helje5** [comment]
That discussion already happened on the mailing list, I don't know why we need to raise it from scratch in here. (and in the context of an overloaded PR, again: please split it off)

A module in Swift defines a 'product' that comes with an implicit namespace. A name of a type should represent what the type is. In this case the request is not just any request, but it is specifically an HTTPRequest. Hence the name.

You mention ObjC and the drop of namespaces. That is a actually a great example on how to do this properly. "NSHTTPURLResponse" in Swift is now properly split into the product/module (NS, now Foundation) and the name of the type aka 'what this type is': `HTTPURLResponse`.

Prefixing types with their namespace is rarely necessary. In contrary, it only becomes necessary if people use overly generic names like `Request`. And that should be avoided at all cost.
This is particularly true in server side endpoints where you will often deal with different kinds of requests. Like the nice and clean:

```
func handleRequest(_ req: HTTPRequest) -> HTTPResponse {
  let fetchRequest = FetchRequest(qualifierFormat: "...")
  ... do fetch ...

  let googleTheResult = GoogleMapsRequest(x, y)
  ... do this ...
}
```

vs the eye bleeding:

```
func handleRequest(_ req: HTTP.Request) -> HTTP.Response {
  let fetchRequest = CoreData.Request(qualifierFormat: "...")
  ... do fetch ...
  let googleTheResult = GoogleMaps.Request(x, y)
}
```

(The GoogleMapsRequest is another prime example for why this is a bad idea. A potential 'Google' module would likely provide different kinds of `Request` objects, e.g. a GoogleMapsRequest, GoogleSearchRequest, etc. which may use a general `GoogleRequest` protocol, to encapsulate what is common between the Google requests (auth and such))

A module namespace avoids clashes between products (e.g. there may be a Vapour implementation of HTTPRequest and a Zewo implementation of the same). It should not affect naming things for what they are.

Module namespace qualification should be the absolute exception, not the rule.

P.S.: FWIW this is common practice in existing languages providing namespaces. E.g. in Java you still use `HttpRequest`, and that even has hierarchical namespaces: [HttpRequest](http://netty.io/4.1/api/io/netty/handler/codec/http/HttpRequest.html). It also showcases very well how namespaces are used for organising products and modules, not for naming types (`io.netty.xyz`).

Other examples:
- JavaScript: [XMLHttpRequest](https://www.w3schools.com/xml/xml_http.asp)
- Python: [httplib.HTTPResponse](https://docs.python.org/2/library/httplib.html#httpresponse-objects)

**Comment by tanner0101** [comment]
Why so many thumb emojis? haha

> Swift is now properly split into the product/module (NS, now Foundation) and the name of the type aka 'what this type is': HTTPURLResponse

Comparing HTTP to Foundation is comparing apples to oranges. Foundation is an absolutely giant module that contains multiple request types in it. So it makes sense that they need a further layer of prefixing to disambiguate. However that's not indicative of good namespacing, that's indicative of low modularity (which is fair seeing as how that code has been around forever).

Every type in this module prior to this PR had an HTTP prefix. Not just a few. I think that's a telling indication that HTTP is being used as a namespace.

> Prefixing types with their namespace is rarely necessary. In contrary, it only becomes necessary if people use overly generic names like Request.

Exactly. If you're only working with HTTP, then you can omit the prefix and your code is beautiful. 

> vs the eye bleeding:

How is `HTTPRequest` any less "eye bleeding" than `HTTP.Request`? The difference there is one period. What seems more "eye bleeding" to me is this code:

```swift
import HTTP

func handleHTTPRequest(_ req: HTTPRequest) -> HTTPResponse {
    return HTTPResponse(...)
}
```

The amount of times HTTP is repeated is really overwhelming for a snippet of code that in this case (only HTTP is imported) cannot be ambiguous with any other type of request or response.

Compare this to:

```swift
import HTTP

func handle(_ req: Request) -> Response {
    return Response(...)
}
```

^ not only objectively less code but I'd say it's way easier to understand what is happening here at first glance.

> (The GoogleMapsRequest is another prime example for why this is a bad idea. A potential 'Google' module would likely provide different kinds of Request objects, e.g. a GoogleMapsRequest, GoogleSearchRequest, etc. which may use a general GoogleRequest protocol, to encapsulate what is common between the Google requests (auth and such))

Why would it be `Google.GoogleMapsRequest`? That's again overly redundant. Why not just `Google.MapsRequest`? 

> A module namespace avoids clashes between products (e.g. there may be a Vapour implementation of HTTPRequest and a Zewo implementation of the same). It should not affect naming things for what they are.

What do you mean by "It should not affect naming things for what they are"? Can you cite any sources or API guidelines that back that up?

> WIW this is common practice in existing languages providing namespaces. E.g. in Java you still use HttpRequest

Java is ancient. 

It looks pretty clear to me the languages and frameworks of the future prefer utilizing namespaces to reduce redundant noise and make code more beautiful:
- Go: [http.Request](https://golang.org/pkg/net/http/#Request)
- Rust/Hyper: [http.request](https://github.com/hyperium/hyper/blob/master/src/http/request.rs#L11)
- Crystal/Kemal: [HTTP::Request](https://github.com/kemalcr/kemal/blob/cf2144636d9d5cef9d8b3f7b3404b003cedb3760/spec/route_handler_spec.cr#L8)

**Comment by paulofaria** [comment]
Haha! Man I'm really torn about this issue. I'm really 51/49. Personally, I prefer without the prefix, but I also get the counter-arguments. But then again, while module names are not namespaces per se, they do work like namespaces when there's ambiguity.

By the way you're both using fallacies in your arguments.

Helge is using [argumentum ad antiquitatem](https://en.wikipedia.org/wiki/Appeal_to_tradition) and Tanner is using the opposite [argumentum ad novitatem](https://en.wikipedia.org/wiki/Appeal_to_novelty). Both arguments about tradition/novelty are not valid, in my opinion. We should strive for best technical solutions. Unfortunately both solutions are sound technically. Only one is more aesthetically pleasing for some (a completely subjective issue as we can see by the different eye-bleeds presented here). So this makes it a bit hard to find the optimal solution for this debate, since it comes down to subjective values.

**Comment by paulofaria** [comment]
Only thing I can think is that the solution for this impasse would be to flip a coin and let it decide prefix or no prefix, and then the unfortunate party can be happy again by _typealiasing_ all types. 😝

**Comment by helje5** [comment]
> Why so many thumb emojis?

That is called voting and a great way to collect opinions and comments and how the approval distributes. (When counting totals just keep in mind that my thumb ups are worth 3 and my thumb downs are worth 5.)

**Comment by tanner0101** [comment]
> Only thing I can think is that the solution for this impasse would be to flip a coin.

I wish there were a way we could poll the community and vote on the issue. But I could get behind flipping a coin! The odds of winning a coin flip are infinitely higher than me convincing @helje5 to change his mind 😛 

I think the heart of this issue is a disagreement about how modules should be used. i.e., whether they are:
- strictly a namespace for resolving rare duplicate symbol issues, or
- a way of nesting and optionally prefixing type names (when compiler detects ambiguity).

I believe Swift's modules are more sophisticated than just being a namespace. I think, used correctly, they can make code more concise, readable, and understandable. 

But I'd really love to hear from someone that works on Swift to get their opinion. Comparing Swift to any other language is silly. Swift is Swift.

**Comment by helje5** [comment]
The comparison with Java was only made because someone claimed that proper naming is a side effect of a language not having namespaces. Which simply isn't the case as demonstrated.

In the end we should stick to common Swift practice and the authoritative framework for that (and in consequence what users expect) is Foundation. Nothing more needs to be said IMO.

BTW: I'm OK w/ using explicit namespaces. I prefer the other, but this would be OK w/ me:

```
enum HTTP {
  class Request {}
}
```

It allows name relative access when using extensions and within the namespace, but makes sure that the calling side uses the actual name and allows the user to identify what kind of 'request' the code is talking about.

**Comment by tanner0101** [comment]
So far this thread has 3 for and 1 against. @seabaylea is there a protocol for voting on such things?

**Comment by seabaylea** [comment]
The standard protocol is to reach consensus, and where the really can't be achieved we go with the majority.

In this instance we need to think about what approach is the least ambiguous to not just a developer creating an applicaiton using the API, but subsequent developers reading their code - and which approach is less ambiguous.

If we had a server framework application that was handling incoming Requests, and that application also made outbound requests using something like Alamofire (which has a Request type), what approach would make the code most readable?

**Comment by tanner0101** [comment]
> In this instance we need to think about what approach is the least ambiguous to not just a developer creating an applicaiton using the API, but subsequent developers reading their code - and which approach is less ambiguous.

The ability to opt-in to adding the `HTTP.` prefix when the developer (or the compiler) finds ambiguity is the ideal solution in my opinion. It gives the developer the choice. 

> If we had a server framework application that was handling incoming Requests, and that application also made outbound requests using something like Alamofire (which has a Request type), what approach would make the code most readable?

Ideally Alamofire would use the `HTTP.Request` from this package, but I see what you mean. Although I think it's equally as ambiguous in both cases.

It sounds like there was a discussion about this I missed on `swift-server-dev`. Is there a link anywhere to that?

**Comment by seabaylea** [comment]
I _think_ this was the start of the relevant thread:
https://lists.swift.org/pipermail/swift-server-dev/Week-of-Mon-20170522/000466.html

**Comment by tanner0101** [comment]
The gods [have spoken](https://twitter.com/tanner0101/status/875041249983684608) and they agree with @helje5.

I'm definitely with @paulofaria in that it's a close one. Probably 60/40 for me in favor of `HTTP.Request`. But I can get behind the core Swift Server APIs being extra unambiguous. Also matching Foundation (even if it is quite an old and brobdingnagian module) seems like the right move for consistency. 

I've created a PR with just the module cleanup here: https://github.com/swift-server/http/pull/9.

Unless anyone else objects, I think this PR can be closed.

**Comment by seabaylea** [comment]
Ahh, so "resort to Twitter" is the new coin flip ;-)

This is definitely a conversation worth us having - and one me may well revisit when we have some real user feedback from people trying to use the APIs.

**Comment by seabaylea** [comment]
Looking like we've got agreement to close this for now and spin off just the addition on the HTTP module under #9

**Comment by hfossli** [comment]
> >Swift is now properly split into the product/module (NS, now Foundation) and the name of the type aka 'what this type is': HTTPURLResponse

> Comparing HTTP to Foundation is comparing apples to oranges. Foundation is an absolutely giant module that contains multiple request types in it. So it makes sense that they need a further layer of prefixing to disambiguate. However that's not indicative of good namespacing, that's indicative of low modularity (which is fair seeing as how that code has been around forever).

I second this!!

> But I'd really love to hear from someone that works on Swift to get their opinion. Comparing Swift to any other language is silly. Swift is Swift.

I second this!!

> The ability to opt-in to adding the HTTP. prefix when the developer (or the compiler) finds ambiguity is the ideal solution in my opinion. It gives the developer the choice.

Yep! 

> The gods have spoken and they agree with @helje5.

What? No, the discussion was confusing, not conclusive and among 4 people on a very specific subtopic.

> (From Twitter) Unless you intend for everybody to qualify the API with the module name, I vote HTTPRequest

He's basically saying that if you *have* to write `HTTP.Request` or `HTTPRequest` every time then he prefers the latter. He basically does not support the `HTTP`-enum, but doesn't say anything about `HTTP`-module where `HTTP` is something you opt-in to.

> (From Twitter) Make an HTTP enum and put Request in it.

 That's a terrible idea. It does not solve anything. It is not better to write `HTTP.Request` over `HTTPRequest`. I hope we can agree on that. It is on the other hand better to be able to *opt-in* in to writing `HTTP.Request` if there's ambiguity with `Request`. The discussion on twitter didn't touch this at all.

> https://lists.swift.org/pipermail/swift-server-dev/Week-of-Mon-20170522/000466.html

The discussion is not well arranged. Just a subset of the same people as in this discussion. Doesn't change anything :-) 

------

I would advise you to ask the authors and contributors of Foundation to get an opinion from them. Maybe @DougGregor, @itaiferber, @dabrahams got an opinion on this. 

There's been released some notes on best practices for naming within a module, but I'm not sure if there's been any on modules.

Some links
https://github.com/raywenderlich/swift-style-guide#class-prefixes
https://twitter.com/clattner_llvm/status/474730716941385729
https://swift.org/documentation/api-design-guidelines/#promote-clear-usage

Some discussion here as well
https://twitter.com/chris__bailey/status/915529122197028864

So far the response in another forum seems to be in favor of approving this PR

skjermbilde 2017-10-04 kl 19 19 38

**Comment by helje5** [comment]
> > (From Twitter) Unless you intend for everybody to qualify the API with the module name, I vote HTTPRequest

> He's basically saying that if you have to write HTTP.Request or HTTPRequest every time then he prefers the latter.

No, he is saying **unless** you intend *everyone* to *write* `HTTP.Request`, use `HTTPRequest`.

He would be fine if `HTTP.Request` would be spelled out all the time, and I share that reasoning. I really don't care whether it is `HTTP.Request` or `HTTPRequest`, in fact I have a slight preference for the former. The thing which is a no-go is having a non-distinct `Request` flying around in the source. That should be avoided, particularly in the server scenario, where you always have multiple kinds of requests flying around (e.g. FetchRequest's etc).

**Comment by hfossli** [comment]
But everybody doesn't not have to qualify the API with the module name. Yes, many may have to, but not everybody.

**Comment by hfossli** [comment]
> The thing which is a no-go is having a non-distinct Request flying around in the source. That should be avoided, particularly in the server scenario, where you always have multiple kinds of requests flying around (e.g. FetchRequest's etc).

That is a subjective opinion and not a no-go? And well, if it is confusing and the developer wants clarity he can always slap a `HTTP.` prefix on. How to achieve clarity should be up to the developer. Long names does not necessarily make it more clear.

**Comment by helje5** [comment]
I explained that in great detail above already (look for products vs namespaces). In this case HTTP is not a product prefix. It simple is what the thing is, not some arbitrary `Request`, but specifically an `HTTPRequest` with all the attached assumptions. That is why you spell that out, not because it happens to live in a module providing the product.

**Comment by hfossli** [comment]
I don't understand what you are saying about products vs namespaces. It might be a bit too abstract for me. Sorry, can you go into more detail? 🙇  With the module-approach the resolved name for `Request` is `HTTP.Request` and I don't see how that is ambiguous as a product. Within this project, how many other `Request`-like classes are there? From what I can see there's only one. 

skjermbilde 2017-10-04 kl 19 54 24

**Comment by helje5** [comment]
Not sure where this is abstract, as mentioned I explained that in great detail above (helje5 commented on Jun 14)? Please read the whole thing, this was already the second iteration over this back then.

> With the module-approach the resolved name for Request is HTTP.Request and I don't see how that is ambiguous as a product. Within this project, how many other Request-like classes are there? From what I can see there's only one.

I agree that *within* the module implementation itself, `Request` would be sufficient. And you can easily accomplish that:

    internal typealias Request = HTTPRequest

The part which is highly undesirably is leaking that to the **API**.

Another solution to this would be the `enum` (explicit namespace) approach I mentioned (but I think it is overkill and not really desirable).
This way the API consumer would have to always write `HTTP.Request` etc, while implementations can use the local name. This is kinda nice because it even allows outside extensions to enhance the API while maintaining the implementation/API naming, but on the other side enum-namespaces are really hacky language wise (maybe Swift 5 brings us distinct namespaces? ;-) )

**Comment by hfossli** [comment]
Yep. I read what you wrote over and over and I still don't get what you are trying to say.  As you know, there's a sender and receiver when communicating. As a receiving part I'm failing to understand what you are trying to say. That may be because I'm stupid, but it may also be that I'm lacking some key context here or that the communication isn't clear.

Just to be clear we now have 5 alternatives, right?

**1. Modulename `HTTP` and prefix `HTTP`**
Fully resolved name `HTTP.HTTPRequest`
Shortest possible reference on the consumer side: `HTTPRequest`
```swift
class HTTPRequest { }
```

---- 
**2. Modulename `HTTP` and prefix `HTTP` with internal typealias**
Fully resolved name `HTTP.HTTPRequest`
Shortest possible reference on the consumer side: `Request`
```swift
class HTTPRequest { }
internal typealias Request = HTTPRequest
```

---- 
**3. Modulename `HTTP` and prefix `HTTP` with public typealias**
Fully resolved name `HTTP.HTTPRequest`
Shortest possible reference on the consumer side: `Request`
```swift
class HTTPRequest { }
public typealias Request = HTTPRequest
```

Pros
+ Easy to opt-in to achieve clarity
+ Users can choose wether to write `HTTP.Request` or `HTTPRequest` or `HTTP.HTTPRequest`

Cons
- clutters autocomplete. Now `HTTP` autocompletes for `HTTP.` and `HTTP[a-z]`

---- 
**4. Modulename `HTTP` and no prefix**
Fully resolved name `HTTP.Request`
Shortest possible reference on the consumer side: `Request`
```swift
class Request { }
```

Pros
+ Easy to opt-in to achieve clarity

---- 
**5. Modulename `HTTP` and enum `HTTP`**
Fully resolved name `HTTP.HTTP.Request`
Shortest possible reference on the consumer side: `HTTP.Request` 
```swift
enum HTTP {
    class Request { }
}
```

---- 

You are in favor of alternative 1 or 2, right? I'm in favor of alternative 4. All I care about is the *API consuming* part. 

> The part which is highly undesirably is leaking that to the API.

Can you elaborate? 

> maybe Swift 5 brings us distinct namespaces?

What are the limitations with current swift version? I don't get it.

---- 

Why do I even care about this? Because it really doesn't feel "swifty". For me this doesn't resonate with Swift philosophy as I know it. "Clarity" is important, but being "concise" is also very important. It is actually important to omit needless words if they do not provide more clarity. That exercise is maybe a subjective one. I don't think the added verbosity of prefixing with `HTTP` is worth the sacrifice. 

Anyways, I want to thank you guys for the effort you've put into this library. Good architectural choices and easy to follow and understand the code all the way.  Good job. Keep it up. Much love. ❤️

**Comment by helje5** [comment]
> You are in favor of alternative 1 or 2, right? 

1, 2, 5 is OK too. As long as the subject is named not ambiguously on the API consuming side.

>> maybe Swift 5 brings us distinct namespaces?

> What are the limitations with current swift version?

Current Swift doesn't provide a distinct namespace concept like C++ or Java do. You can fake it using the case-less enum, but I consider that a hack.

>  "Clarity" is important, but being "concise" is also very important.

I agree with that, and I consider the HTTP in HTTPRequest a vital part of what the type is. As I said before, this is not just some request, but specifically an HTTPRequest (i.e. with headers and a body stream, a method).

What module (product) that is provided from, doesn't matter for the naming. E.g. Vapor may have a HTTPRequest and a FetchRequest, ApacheExpress may provide an HTTPRequest and a FetchRequest based on mod_dbd and so on. And if you use them together you may rarely need to disambiguate the two versions from each other. But they both are still HTTPRequests. Name stuff after what they do, not something as 'generic' as Request. Or Any, which would be almost as good ;-)

**Comment by tanner0101** [comment]
This might be out of context (haven't been paying close attention to this thread for a while) but I would like to share that we (vapor core team) are likely going to change our code style for `vapor/*` packages to match this package more closely.

Although I was originally a big proponent of `HTTP.Request` (where `HTTP` is the module), in practice, this can be quite a hassle and has bad discoverability. 

In Vapor 3, we're opting for more descriptive type names (even if redundant w/ the module name). For example, `SQLite.Connection` -> `SQLiteConnection`. `Fluent.Connection` -> `DatabaseConnection`. 

Hopefully Swift gets a better name spacing system soon (something like Java or Go), but until then, it seems like the designers of the language really only want you to use module name disambiguation where no other solution is possible.

**Comment by hfossli** [comment]
Well, discoverability is bad in Swift in general. I don’t think that should be solved this way on framework level. That’s on Swift. It will probably get a lot better. 

For example I tend to write `String.init` for autocomplete to tell me which init methods there are on String. If I just write `String` I don’t get the same discoverability. After I discover I remove `init`. 

Likewise I would discover http classes and definitions by writing `http.` (and then maybe remove `http` if it is redundant).

**Comment by hfossli** [comment]
I would agree with you guys if this library wasn't so well scoped. This library is only about HTTP requests. I would agree if this module wasn't named `HTTP`. If it were something humongous like Foundation then it would definitely make sense. If it had a different name (e.g. `Server`) I would agree it made sense to prefix everything with `HTTP`.

BUT as it stands now – so well defined and well scoped – it doesn't make sense to me. 

My final word of advice is to let the user of this library disambiguate on his/her own. Let them opt-in and slap the `HTTP`-module on instead of forcing them to write `HTTPRequest`, `HTTPServer`etc.

**Comment by hfossli** [comment]
Some thoughts on this topic in a podcast https://spec.fm/podcasts/swift-unwrapped/89166 😆

**Pull request closed without merging**
